Adapt to binutils bfd_get_section_vma() and bfd_get_section_flags() macro changes
Adapt to binutils bfd_get_section_vma() and bfd_get_section_flags()
macro changes. The old macros are:
  #define bfd_get_section_vma(bfd, ptr) ((ptr)->vma + 0)
  #define bfd_get_section_flags(bfd, ptr) ((ptr)->flags + 0)

And the new ones are:
  #define bfd_get_section_vma(bfd, ptr) ((void) bfd, (ptr)->vma)
  #define bfd_get_section_flags(bfd, ptr) ((void) bfd, (ptr)->flags)

This was causing the build to fail:
src/rtrace-resolve/resolver.c: In function ‘bfd_get_address_info’:
src/rtrace-resolve/resolver.c:354:8: error: ‘resolver’ undeclared (first use in this function)
src/rtrace-resolve/resolver.c:354:8: note: each undeclared identifier is reported only once for each function it appears in
src/rtrace-resolve/resolver.c:354:8: warning: left-hand operand of comma expression has no effect [-Wunused-value]
src/rtrace-resolve/resolver.c:357:9: warning: left-hand operand of comma expression has no effect [-Wunused-value]